name = "OckleberryModsIII"
author = "Ockleberry and Friends"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1392fe2d77a21d2b204f6c536959a7e7950983d6e04e5aaf994765c2370b482"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
